# Generated by ariadne-codegen
# Source: src/planpilot/core/providers/github/operations

from typing import Optional

from pydantic import Field

from .base_model import BaseModel


class UpdateProjectIterationField(BaseModel):
    update_project_v_2_item_field_value: Optional["UpdateProjectIterationFieldUpdateProjectV2ItemFieldValue"] = Field(
        alias="updateProjectV2ItemFieldValue"
    )


class UpdateProjectIterationFieldUpdateProjectV2ItemFieldValue(BaseModel):
    project_v_2_item: Optional["UpdateProjectIterationFieldUpdateProjectV2ItemFieldValueProjectV2Item"] = Field(
        alias="projectV2Item"
    )


class UpdateProjectIterationFieldUpdateProjectV2ItemFieldValueProjectV2Item(BaseModel):
    id: str


UpdateProjectIterationField.model_rebuild()
UpdateProjectIterationFieldUpdateProjectV2ItemFieldValue.model_rebuild()
